config/routes.rb
DirtyLaundry::Application.routes.draw do

  get 'application' => 'application#home', as: :splash
  get 'nyc' => 'application#nyc', as: :nyc
  root "application#home" 

  post 'users/create' => 'users#create'
  get 'users/new' => 'users#new', as: :sign_up
  get 'sessions/new' => 'sessions#new', as: :log_in
  delete 'sessions' => 'sessions#destroy', as: :log_out
  get '/auth/:provider/callback' => 'authentications#create'

  resources :scans

  get '/dashboard/current' => 'dashboards#current', as: :current_dashboard
  get '/dashboard/:id' => 'dashboards#summary', as: :dashboard
  get '/dashboard/:id/analytics' => 'dashboards#analytics'
  get '/dashboard/:id/locations' => 'dashboards#locations'
  get '/dashboard/:id/connections' => 'dashboards#connections'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user


end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  # POST /authentications
  # POST /authentications.json
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'],omniauth['uid'])

    ### User had already been authenticated
    if authentication
      authentication.user.twitter_detail.update(TwitterDetail.omniauth_attributes(omniauth))
      flash[:notice] = "Sign in Successful"
      login(authentication.user)
      redirect_to :new_scan

    ### User needed authenticating but was signed in
    elsif current_user
      current_user.authentications.create!(provider: omniauth['provider'],uid: omniauth['uid'])
      user.twitter_detail.update(TwitterDetail.omniauth_attributes(omniauth))
      flash[:notice] = "Sign in Successful"
      redirect_to :new_scan

    ### User needed authenticating and wasn't signed in yet
    else
      user = User.new(User.omniauth_attributes(omniauth))
      user.authentications.build(provider: omniauth['provider'],uid: omniauth['uid'])
      user.twitter_detail = TwitterDetail.new(TwitterDetail.omniauth_attributes(omniauth))
      if user.save
        flash[:notice] = "Sign up Successful"
        login(user)
        redirect_to :new_scan
      else
        flash[:alert] = "Sign up Unsuccessful. Please try again."
        redirect_to :log_in
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_authentication
    @authentication = Authentication.find(params[:id])
  end
end

app/views/authentications/index.html.erb
<h1>Listing authentications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Provider</th>
      <th>Uid</th>
      <th>Index</th>
      <th>Create</th>
      <th>Destroy</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authentications.each do |authentication| %>
      <tr>
        <td><%= authentication.user_id %></td>
        <td><%= authentication.provider %></td>
        <td><%= authentication.uid %></td>
        <td><%= link_to 'Show', authentication %></td>
        <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
        <td><%= link_to 'Destroy', authentication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>