config/routes.rb
DirtyLaundry::Application.routes.draw do

  get 'application' => 'application#home', as: :splash
  get 'nyc' => 'application#nyc', as: :nyc
  root "application#home" 

  post 'users/create' => 'users#create'
  get 'users/new' => 'users#new', as: :sign_up
  get 'sessions/new' => 'sessions#new', as: :log_in
  delete 'sessions' => 'sessions#destroy', as: :log_out
  get '/auth/:provider/callback' => 'authentications#create'

  resources :scans

  get '/dashboard/current' => 'dashboards#current', as: :current_dashboard
  get '/dashboard/:id' => 'dashboards#summary', as: :dashboard
  get '/dashboard/:id/analytics' => 'dashboards#analytics'
  get '/dashboard/:id/locations' => 'dashboards#locations'
  get '/dashboard/:id/connections' => 'dashboards#connections'

end

app/models/scan.rb
class Scan < ActiveRecord::Base
  belongs_to :user
  has_many :tweets, :dependent => :destroy
  has_one :twitter_detail, :dependent => :destroy

  @@stream_running

  def initialize_twitter_stream
    @client = Tweet.initialize_streaming_twitter_client

    topics = ["coffee", "tea"]
    i = 0
    @@stream_running = true
    @client.filter(:track => topics.join(",")) do |object|
      if object.is_a?(Twitter::Tweet)
        puts object.text if object.is_a?(Twitter::Tweet)
        parse_and_save_tweet(object) if object.is_a?(Twitter::Tweet)
        puts i.to_s
        i+= 1
      end
      break if i >= 100
    end
    @@stream_running = false
  end

  def stream_running
    @@stream_running
  end

  def stream_running=(bool)
    @@stream_running = bool
  end

  def run
    @client = Tweet.initialize_twitter_client
    puts "Scan: #{self.id} - Twitter Client established"
    # return unless user_exsts?

    get_users_statuses
    puts "Scan: #{self.id} - Tweets Retrieved and Processed"

    # get_users_connections

  end

  # def user_exsts?
  #   # begin
  #     @user = @client.user(self.username)
  #     self.error = "Success"
  #     self.twitter_detail = TwitterDetail.new(TwitterDetail.user_attributes(@user))
  #     true
  #   # rescue
  #   #   self.error = "Does Not Exist"
  #   #   false
  #   # end
  # end

  def get_users_statuses
    return if self.twitter_detail.protected_tweets

    sentiment_analyzer = Sentimental.new

    full_tweets = Tweet.get_all_tweets_for_user(self.username)
    total_score = 0
    total_sentiment = 0

    full_tweets.each do |t|

      # Create Tweet Objects
      new_tweet = Tweet.new(text: t.full_text, tweet_time: t.created_at,
                            twitter_id: t.id, scan_id: self.id)

      # Set geolocation if applicable
      new_tweet.has_geo = t.geo? ? new_tweet.record_geolocation(t.geo) : false

      # Scan for Sentimentality
      total_sentiment += new_tweet.score_sentimentality(sentiment_analyzer)

      # Scan for Obscenities
      total_score += new_tweet.count_obscenities

      # Scan for Hashtags, Mentions, and Links
      new_tweet.start_twitter_text_scan

      # Find popular links - instagram, twitpic
      # Find all people mentioned
      # Common words used

      new_tweet.save
    end
    self.score = total_score
    self.average_sentiment = total_sentiment / self.tweets.count
  end

  def get_users_connections
    # GET friends/list -> Following usernames+descriptions
    # GET followers/list -> Followers
    # GET users/lookup -> hydrated user object
    # Check if mentioned people are verified
  end

  def total_dirty_word_count
    x = 0
    self.tweets.each{|i| i.dirty_word_count + x}
    x
  end

  def parse_and_save_tweet(twitter_object)
    return if twitter_object.nil?

    sentiment_analyzer = Sentimental.new

    # Create Tweet Objects
    new_tweet = Tweet.new(text: twitter_object.full_text,
                          tweet_time: twitter_object.created_at,
                          twitter_id: twitter_object.id,
                          scan_id: self.id)

    # Set geolocation if applicable
    new_tweet.has_geo = twitter_object.geo? ? new_tweet.record_geolocation(twitter_object.geo) : false

    # Scan for Sentimentality
    new_tweet.score_sentimentality(sentiment_analyzer)

    # Scan for Obscenities
    new_tweet.count_obscenities

    # Scan for Hashtags, Mentions, and Links
    new_tweet.start_twitter_text_scan

    # Find popular links - instagram, twitpic
    # Find all people mentioned
    # Common words used

    new_tweet.save
  end

end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  before_action :set_scan, only: [:show, :edit, :update, :destroy]
  before_filter :login_required

  # GET /scans
  # GET /scans.json
  def index
    if current_user.scans.empty? || current_user.username = "corbin_page"
      @scans = Scan.all
    else
      @scans = current_user.scans
    end
  end

  # GET /scans/1
  # GET /scans/1.json
  def show
    redirect_to dashboard_path(params[:id])
  end

  # GET /scans/new
  def new
    @scan = Scan.new
  end

  # GET /scans/1/edit
  def edit
  end

  # POST /scans
  # POST /scans.json
  def create
    @scan = Scan.create(scan_params)
    @scan.user = current_user
    Tweet.initialize_twitter_client
    @user = Tweet.client.user(@scan.username)
    # Need to put in logic if the twitter user does not exist
    @scan.twitter_detail = TwitterDetail.new(TwitterDetail.user_attributes(@user))
    @scan.save
    @scan.run
    # Stalker.enqueue("scan.run", id: @scan.id)
    
    respond_to do |format|
      if @scan.save
        format.html { redirect_to @scan, notice: 'Scan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scan }
      else
        format.html { render action: 'new' }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scans/1
  # PATCH/PUT /scans/1.json
  def update
    respond_to do |format|
      if @scan.update(scan_params)
        format.html { redirect_to @scan, notice: 'Scan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scans/1
  # DELETE /scans/1.json
  def destroy
    puts @scan.inspect
    @scan.destroy
    respond_to do |format|
      format.html { redirect_to scans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scan
      @scan = Scan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scan_params
      params.require(:scan).permit(:username)
    end
end

app/views/scans/_form.html.erb
<%= form_for(@scan) do |f| %>
  <% if @scan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scan.errors.count, "error") %> prohibited this scan from being saved:</h2>

      <ul>
      <% @scan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username, value: "corbin_page" %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scans/dashboard.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview</a></li>
        <li><a href="#">Reports</a></li>
        <li><a href="#">Analytics</a></li>
        <li><a href="#">Export</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="">Nav item</a></li>
      </ul>
      <ul class="nav nav-sidebar">
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <h1 class="page-header">Dashboard</h1>
        <div class="row">
          <div class="col-sm-4">
            <div class="panel panel-default"
              <div class="panel-heading">
                <h3 class="panel-title">Twitter Summary</h3>
              </div>
              <div class="panel-body">
                Placeholder Text
              </div>
          </div>
        </div>
      <h2 class="sub-header">All Tweets</h2>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Text</th>
              <th>Score</th> 
              <th>Dirty Words</th>
              <th>Sentiment Score</th>
              <th>Sentiment Summary</th>
            </tr>
          </thead>
          <tbody>
            <% @scan.tweets.each do |t| %>
              <tr>
                <td><%= t.text %></td>
                <td><%= t.score %></td>
                <td><%= t.dirty_words %></td>
                <td><%= t.sentiment_score %></td>
                <td><%= t.sentiment_summary %></td>
              </tr>
            <% end %>  
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/scans/edit.html.erb
<h1>Editing scan</h1>

<%= render 'form' %>

<%= link_to 'Show', @scan %> |
<%= link_to 'Back', scans_path %>

app/views/scans/index.html.erb
<div class="jumbotron">
  <div class="container">

    <h1>All My Scans</h1>

    <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Username</th>
          <th>Sketch Score</th>
          <!-- <th>Average Sentiment (-3 to 3)</th> -->
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @scans.each do |scan| %>
          <tr>
            <td><%= scan.username %></td>
            <td><%= scan.score %></td>
            <!-- <td><%= scan.average_sentiment %></td> -->
            <td><%= link_to 'Show', scan %></td>
            <td><%= link_to 'Edit', edit_scan_path(scan) %></td>
            <td><%= button_to 'Destroy', scan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>

    <br>

    <%= link_to 'New Scan', new_scan_path %>
  </div>
</div>

app/views/scans/new.html.erb
<div class="row text-center">
    <%= form_for(@scan,html: {class: "form-signin", role: "form"}) do |f| %>
      <h2 class="form-signin-heading">Start New Scan</h2>
      <% if @scan.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@scan.errors.count, "error") %> prohibited this scan from being saved:</h2>
          <ul>
          <% @scan.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.text_field :username, placeholder: "Twitter Handle", value: current_user.username, class: "form-control", autofocus: true %>
      </div>
      <div class="actions">
        <%= f.submit "Start Scan", class: "btn btn-lg btn-success btn-block" %>
      </div>
    <% end %>
</div>

app/views/scans/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview</a></li>
        <li><a href="#">Reports</a></li>
        <li><a href="#">Analytics</a></li>
        <li><a href="#">Export</a></li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-2 col-sm-9 col-sm-offset-3 twitter-profile">
      <h1><%= @twitter_detail.name%>'s Dashboard</h1>
      <div class="row">
        <div class="col-md-12 col-sm-12 widget">
            <div class="panel panel-primary twitter-summary">
              <div class="panel-heading">Twitter Summary</div>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Data</th>
                    <th>Value</th> 
                  </tr>
                </thead>
                <tbody>
                    <tr>
                      <td>Name</td>
                      <td><%= @twitter_detail.name%></td>
                    </tr>
                    <tr>
                      <td>Handle</td>
                      <td><%= @twitter_detail.user_name%></td>
                    </tr>
                    <tr>
                      <td>Description</td>
                      <td><%= @twitter_detail.description%></td>
                    </tr>
                    <tr>
                      <td>Location</td>
                      <td><%= @twitter_detail.location%></td>
                    </tr>
                    <tr>
                      <td>Created At</td>
                      <td><%= @twitter_detail.account_created_at%></td>
                    </tr>
                    <tr>
                      <td># of Followers</td>
                      <td><%= @twitter_detail.followers_count%></td>
                    </tr>
                    <tr>
                      <td># Following</td>
                      <td><%= @twitter_detail.following_count%></td>
                    </tr>
                    <tr>
                      <td>Total Tweets</td>
                      <td><%= @twitter_detail.total_tweets%></td>
                    </tr>
                    <tr>
                      <td># of Favorites</td>
                      <td><%= @twitter_detail.favorites_count%></td>
                    </tr>
                    <tr>
                      <td>Website</td>
                      <td><%= @twitter_detail.website_url%></td>
                    </tr>
                </tbody>
              </table>
            </div>
        </div>
      </div>
    </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-2 col-sm-9 col-sm-offset-3 twitter-profile">
      <h1>Charts</h1>
      <div class="row">
        <%= line_chart @scan.tweets.group_by_month(:tweet_time).count %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-2 col-sm-9 col-sm-offset-3 twitter-profile">
      <h1>All Tweets</h1>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Text</th>
                <th>Score</th> 
                <th>Dirty Words</th>
                <th>Sentiment Score</th>
                <th>Sentiment Summary</th>
              </tr>
            </thead>
            <tbody>
              <% @scan.tweets.each do |t| %>
                <tr>
                  <td><%= t.text %></td>
                  <td><%= t.score %></td>
                  <td><%= t.dirty_words %></td>
                  <td><%= t.sentiment_score %></td>
                  <td><%= t.sentiment_summary %></td>
                </tr>
              <% end %>  
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  </div>
</div>