config/routes.rb
DirtyLaundry::Application.routes.draw do

  get 'application' => 'application#home', as: :splash
  get 'nyc' => 'application#nyc', as: :nyc
  root "application#home" 

  post 'users/create' => 'users#create'
  get 'users/new' => 'users#new', as: :sign_up
  get 'sessions/new' => 'sessions#new', as: :log_in
  delete 'sessions' => 'sessions#destroy', as: :log_out
  get '/auth/:provider/callback' => 'authentications#create'

  resources :scans

  get '/dashboard/current' => 'dashboards#current', as: :current_dashboard
  get '/dashboard/:id' => 'dashboards#summary', as: :dashboard
  get '/dashboard/:id/analytics' => 'dashboards#analytics'
  get '/dashboard/:id/locations' => 'dashboards#locations'
  get '/dashboard/:id/connections' => 'dashboards#connections'

end

app/views/layouts/_dashboard.html.erb
<div class="container-fluid <%=@dashboard_type%>">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar side-nav <%=@dashboard_type%>">
        <li id="summary">
          <a href=<%="/dashboard/#{@scan.id}"%>>Summary
            <div class = "icon">
              <span class="glyphicon glyphicon-home"></span>
            </div>
          </a>
        </li>
        <li id="analytics">
          <a href=<%="/dashboard/#{@scan.id}/analytics"%>>Analytics
            <div class = "icon">
              <span class="glyphicon glyphicon-stats"></span>
            </div>
          </a>
        </li>
        <li id="locations" class="disabled">
          <!-- <a href=<%="/dashboard/#{@scan.id}/locations"%>>Locations -->
          <a name="locations">Locations
            <div class = "icon">
              <span class="glyphicon glyphicon-globe"></span>
            </div>
          </a>
        </li>
        <li id="connections" class="disabled">
          <!-- <a href=<%="/dashboard/#{@scan.id}/connections"%>>Connections -->
          <a name="connections"%>Connections
            <div class = "icon">
              <span class="glyphicon glyphicon-user"></span>
            </div>
          </a>
        </li>
      </ul>
      <% unless @dashboard_type == "summary"%>
      <div class="twitter-sidebar">
        <img class="twitter-profile-pic" src="<%=@scan.twitter_detail.profile_image_url%>" alt="Corbin Page">
        <h4 class="username"><%= @scan.twitter_detail.user_name%></h4>
      </div>
      <%end%>
    </div>
  </div>
  <%= yield %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="navbar-footer">
      <ul class="footer-list">  
        <li><a class="footer-link" href="https://github.com/corbinpage/sketch-meter" target="_blank">About</a></li>
        <li><div class="footer-text">|</div></li>
        <li><a class="footer-link" href="https://twitter.com/corbin_page" target="_blank">Contact</a></li>
      </ul>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Home', root_path%></li>
<li><%= link_to 'My Dashboard', current_dashboard_path%></li>
<li><%= link_to 'New Scan', new_scan_path%></li>
<li><%= link_to 'All My Scans', scans_path%></li>

app/views/layouts/_navigation_right.html.erb
<%if logged_in?%>
<li><%= link_to 'Log Out', log_out_path, method: :delete%></li>
<%else%>
<li><%= link_to 'Sign Up', sign_up_path%></li>
<li><%= link_to 'Log In', log_in_path%></li>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sketch Meter" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dirty Laundry" %>">
    <%= stylesheet_link_tag "application", media: "all"%>
    <%= include_gon %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body role="document" class="background-dark">
    <%= render 'layouts/navigation' %>
    <main role="main" class="container">
       <%= render 'layouts/messages' %>
       <%= controller.sub_layout ? (render :partial => "/layouts/#{controller.sub_layout}") : yield %>
    </main>
      <%= render 'layouts/footer' %>
  </body>
</html>